CREATE TABLE [dbo].[raw_year](
	[year_id] [varchar](128) NOT NULL,
	[action_year] [varchar](20) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[raw_year] ADD  CONSTRAINT [PK_raw_year] PRIMARY KEY CLUSTERED 
(
	[year_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
