CREATE TABLE [dbo].[raw_week](
	[week_id] [varchar](128) NOT NULL,
	[action_week] [varchar](20) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[raw_week] ADD  CONSTRAINT [PK_raw_week] PRIMARY KEY CLUSTERED 
(
	[week_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
